### ISSUE TITLE
Move repository to new organisation - https://github.com/Rendered-Dimension

### ISSUE THREAD

**Issue by thisisabhinay** [Rendered-Dimension/slick2.0#1]
To organise team's game related projects and activities in one place

**Comment by thisisabhinay** [comment]
@VRamazing You need to do following tasks:

- [ ] Assign this issue to yourself 
- [ ] Resolve this issue by EOD today (7 October 2019)

**Comment by thisisabhinay** [comment]
@VRamazing Give me admin access so that I can resolve this issue by myself

**Comment by VRamazing** [comment]
This has been resolved. Hence closing.
