### ISSUE TITLE
Install unity's github plugin and push the local project to this repository

### ISSUE THREAD

**Issue by thisisabhinay** [Rendered-Dimension/slick2.0#2]
Here's the link: https://unity.github.com
Install this plug-in through in editor app store. After importing goto **Window > GitHub**. Do the necessary configurations and push the local code base to this repository.

---
***Note:** It's recommended that you do this task after transferring this repo to new organisation*

**Comment by thisisabhinay** [comment]
Again assign this issue to yourself as I've no contributor access to this repository

**Comment by VRamazing** [comment]
Haven't added github to unity. Pushed manually. Closing this for now.

**Comment by thisisabhinay** [comment]
@VRamazing Do it. It'll take care of what files to move and what not. Very handy and convenient.

**Comment by VRamazing** [comment]
Seems redundant. I already added gitignore to take care of it.

**Comment by thisisabhinay** [comment]
@VRamazing Then it's fine. As you are handling the process manually, this issues seems redundant and therefore can be closed
